name: php build xx IR

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  php-application-build:
    runs-on: ubuntu-latest
    name: Run build with anomalies

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_API_KEY}}
      # ============= InvisiRisk Setup End =============
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
          
      - name: Validate composer.json
        run: composer validate --no-check-publish

      - name: Install dependencies (allow legacy insecure packages)
        run: |
          composer config --global audit.block-insecure false
          composer install --prefer-dist --no-progress --no-interaction

      - name: Show installed PHP version
        run: php -v

      - name: Show Composer version
        run: composer --version
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
